apiVersion: batch/v1
kind: Job
metadata:
  name: rules-generator-job2
  labels:
    app: rules-generator
spec:
  template:
    metadata:
      labels:
        app: rules-generator
    spec:
      containers:
        - name: rules-generator
          image: globson/rules-generator:latest
          env:
            - name: DATASET_NAME
              value: "2023_spotify_ds1.csv"
          volumeMounts:
            - name: rules-volume
              mountPath: /app/rules
      restartPolicy: OnFailure
      volumes:
        - name: rules-volume
          persistentVolumeClaim:
            claimName: rules-pvc
