apiVersion: batch/v1
kind: Job
metadata:
  name: rules-generator-job
spec:
  template:
    metadata:
      labels:
        app: rules-generator
    spec:
      containers:
        - name: rules-generator
          image: globson/rules-generator:0.1
          volumeMounts:
            - name: rules-volume
              mountPath: /app/rules
      restartPolicy: OnFailure
      volumes:
        - name: rules-volume
          persistentVolumeClaim:
            claimName: rules-pvc
