apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rules-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 128Mi
  selector:
    matchLabels:
      namespace: samuelsena
